### ISSUE TITLE
s4sdk/docker-cf-cli - cloudFoundryDeploy org not found

### ISSUE THREAD

**Issue by lewingan** [SAP/cloud-s4-sdk-pipeline-docker#12]
We are using Jenkins pipeline with Project Piper for build and deploy to Cloud Foundry. About a week or so ago the deployment started to fail with org not found (see below). Nothing changed in our pipeline and manually logging in via CLI using the cf login command works fine (org can be targeted).

```
API endpoint:   https://api.cf.eu10.hana.ondemand.com (API version: 2.141.0)
User:           ****
No org or space targeted, use 'cf target -o ORG -s SPACE'
Organization 'XXXXXXXXXX' not found.
FAILED
```

Earlier today I modified the pipeline to use an older version of s4sdk/docker-cf-cli (v24 instead of latest) and the deployment started to work.

Something was changed between v24 and latest that broke the targeting of org/space during cf login.

**Comment by lewingan** [comment]
I will try that image and let you know. By the way the cloudFoundryDeploy step of the Project Piper library states that the default Docker image it uses is as follows

deployTool=cf_native:s4sdk/docker-cf-cli
deployTool=mtaDeployPlugin:s4sdk/docker-cf-cli

If s4sdk is being deprecated maybe this has to be updated too. I am currently using the dockerImage parameter to override this default value.

**Comment by fwilhe** [comment]
Yes, we're still in the process of updating the documentation. Sorry about the inconvenience.

**Comment by lewingan** [comment]
Hi @fwilhe 
I am using ppiper/cf-cli and it works fine - thanks for this.
aside from the documentation might want to make sure that the dockerImage parameter of the cloudFoundryDeploy step does not still default to the old s4sdk/ image.

Thanks
